- name: Deploy argocd Block
  when:
    - ((k3s_control_node and k3s_controller_list | length == 1)
      or (k3s_primary_control_node and k3s_controller_list | length > 1))
  block:
    - name: Add argocd helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm
        force_update: true

    - name: Deploy argocd with helm
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        chart_version: v7.2.0
        values:
          configs:
            secret:
              argocdServerAdminPassword: "{{ argocd_pw }}"
        wait: true
        release_state: present
